services:
  task-manager:
    build: .
    container_name: task-manager-flask-monitoring
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=monitoring-secret-key
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-task-manager
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      - monitoring-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-task-manager
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-task-manager
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
